### ISSUE TITLE
Verbosity of fit and predict

### ISSUE THREAD

**Issue by pbiecek** [olagacek/SAFE#3]
How I can turn off messages in the fit and predict?
It will be good to have three levels: no messages, current messages, more detailed messages with information related to the extracted transformation

**Comment by olagacek** [comment]
Currently there are two levels of verbosity, if argument **verbose** is set to False no messages will be printed, if it is set to True messages containing info about fitted and transformed variables will be printed. To see details about transformations check out **summary()** method.
