### ISSUE TITLE
Summary of the SafeTransformer doesn't display levels

### ISSUE THREAD

**Issue by agosiewska** [olagacek/SAFE#4]
Hi, I am preparing examples of SAFE. It seems to me that `summary()` for SafeTransformer doesn't work properly.

At the end of [this jupyter notebook](https://github.com/agosiewska/SAFE_examples/blob/master/classification_titanic.ipynb) it seems that there are no variable levels for the variable `Sex`.

**Comment by plubon** [comment]
Hi, new version that fixes this issue was released on pip

**Comment by agosiewska** [comment]
Thank you!
